#!/bin/bash

#-#
#-# Java
#-#

# Simple java configuration management

java-config() {
  if [ ! -x /usr/libexec/java_home ]; then
    echo 'Java is not present!'
    return
  fi

  case ${1} in
    6)
      export JAVA_HOME=$(/usr/libexec/java_home -v 1.6)
    ;;
    7)
      export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)
    ;;
    8)
      export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
    ;;
    fast)
      export JAVA_OPTS="-d32 -client -Djruby.compile.mode=OFF"
    ;;
    heap)
      if [ -z "$2" ]; then
        $2 = 1024
      fi
      export JAVA_OPTS="-Xmx${2}m"
    ;;
    nopts)
      unset JAVA_OPTS
    ;;
    versions)
      /usr/libexec/java_home --verbose
     ;;
  esac

  java -version
}


#-#
#-# Files
#-#

# Show hidden files in OSX Finder

if [[ $SYSTEM_OS -eq 'Darwin' ]]; then
  function showhidden {
    if [ -z "$1" ]; then
      echo "Usage: showhidden <true|false>"
    else
      if [[ $1 -eq 'true' ]]; then
        defaults write com.apple.finder AppleShowAllFiles YES
      else
        defaults write com.apple.finder AppleShowAllFiles NO
      fi
    fi
  }
fi


#-#
#-# Misc
#-#

# Simple calculator

= () {
  echo "$*" | bc -l
}
