#!/bin/bash

#-#
#-# Color settings
#-#

# Enable terminal colors
export CLICOLOR=1

# Enable ls coloring
export LSCOLORS=exfxcxdxbxegedabagacad
export LS_COLORS='di=34;40:ln=35;40:so=32;40:pi=33;40:ex=31;40:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43:'

# Enable grep coloring
export GREP_OPTIONS='--color=always'
export GREP_COLOR='1;31'


#-#
#-# Editor
#-#

export EDITOR=vim


#-#
#-# Maven
#-#

export M2_HOME=/usr/local/apache-maven/
export M2=$M2_HOME/bin
export PATH=$M2:$PATH


#-#
#-# Java
#-#

export JAVA_HOME=$([ -x /usr/libexec/java_home ] && /usr/libexec/java_home -v 1.7)


#-#
#-# History
#-#

export HISTCONTROL=ignoredups
shopt -s histappend

#-#
#-# Man pages
#-#

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# Color man pages
export LESS_TERMCAP_mb=$(printf "${COLOR_LIGHT_RED}")              # begin blinking
export LESS_TERMCAP_md=$(printf "${COLOR_LIGHT_RED}")              # begin bold
export LESS_TERMCAP_me=$(printf "${COLOR_NC}")                     # end mode
export LESS_TERMCAP_se=$(printf "${COLOR_NC}")                     # end standout-mode
export LESS_TERMCAP_so=$(printf "${BACKGROUND_RED}${COLOR_WHITE}") # begin standout-mode - info box
export LESS_TERMCAP_ue=$(printf "${COLOR_NC}")                     # end underline
export LESS_TERMCAP_us=$(printf "${COLOR_LIGHT_GREEN}")            # begin underline


#-#
#-# Misc
#-#

# Hack to get rid of the annoying TMOUT
unset TMOUT > /dev/null 2>&1

if [[ $? -ne 0 ]]
then
  gdb <<EOF > /dev/null 2>&1
attach $$
call unbind_variable("TMOUT")
detach
quit
EOF
fi
