#!/bin/bash

#-#
#-# Prompt
#-#

export PROMPT_BASE="\[${COLOR_BLUE}\]\u\[${COLOR_NC}\]@\[${COLOR_BLUE}\]\h\[${COLOR_NC}\]:\w"
export PROMPT_GIT="\$(git branch 2>/dev/null | sed -n '/^*/p' | sed 's/* /:\[${COLOR_GREEN}\]/g')"
export PROMPT_END="\[${COLOR_NC}\]\$ "