#!/bin/bash

if [[ "${USER}" == "root" ]]; then
  USER_COLOR="${COLOR_RED}"
else
  USER_COLOR="${COLOR_BLUE}"
fi

if [[ "${SSH_TTY}" ]]; then
  HOST_COLOR="${COLOR_RED}"
else
  HOST_COLOR="${COLOR_BLUE}"
fi

PROMPT_BASE="\[${USER_COLOR}\]\u\[${COLOR_NC}\]@\[${HOST_COLOR}\]\h\[${COLOR_NC}\]:\w"
PROMPT_GIT="\[${COLOR_GREEN}\]$(get_git_repository_details)"
PROMPT_END="\[${COLOR_NC}\]\$ "

[ "${PROMPT_GIT}" != "\[${COLOR_GREEN}\]" ] && PROMPT_GIT=":${PROMPT_GIT}"

export PS1="${PROMPT_BASE}${PROMPT_SVN}${PROMPT_GIT}${PROMPT_END}"
